### PR TITLE
#4932 fix @mention being displayed twice if the name has a TM symbol

### LINKED ISSUE #4932: @ing someone that has a TM symbol in their display name will print their name twice
### Environment

Second Life Release 7.2.2.18475198968 (64bit)
Release Notes

You are at 117.3, 88.9, 21.8 in By Design located at simhost-0caa2e4080ef1beab.agni
SLURL: http://maps.secondlife.com/secondlife/By%20Design/117/89/22
(global coordinates 261,493.0, 246,873.0, 21.8)
Second Life Preflight 2025-09-26.18046863877
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.92 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.6456)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.6590
OpenGL Version: 4.6.0 NVIDIA 565.90

Window size: 1831x1484
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 8192MB
Disk cache: Max size 11468.8 MB (10.9% used)

J2C Decoder Version: KDU v8.4.1
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.24.2 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.24.0.202510081738
  CEF: 139.0.40+g465474a+chromium-139.0.7258.139
  Chromium: 139.0.7258.139
LibVLC Version: 3.0.21
Voice Server Version: Not Connected
Packets Lost: 0/5,059 (0.0%)
November 04 2025 13:04:30

### Description

@ing someone that has a TM symbol in their display name will print their name twice.

### Reproduction steps

1. Set your display name to Name™
2. Relog so you see your new display name.
3. In chat, type @ and choose your name

Issue 1 observed: your cursor is between your display name and the real name. 
Expected: The cursor should be at the end of the line.

4. Move your cursor to the end of the line, type hi, and hit enter.

Issue 2 observed: The chat output is: @Name™ (testerd1.tester)™@Name™ (testerd1.tester) hi
Expected: @Name™ (testerd1.tester) hi

Image

Video: https://github.com/user-attachments/assets/74737c07-8234-45a3-a58c-72111478ae81
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #4932</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @Dan-Linden</code> (replace <code>20</code> with the amount, and <code>@Dan-Linden</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by maxim-productengine**
Currently only mentions use highlight background style (determine via `getDrawHighlightBg()`), so let's alter only that segments.

### CODE REVIEW

**Review by akleshchev — APPROVED** [review]

**Review by marchcat — APPROVED** [review]

File: indra/llui/lltextbase.cpp [hunk 1]
```diff
@@ -3521,6 +3520,11 @@ LLNormalTextSegment::LLNormalTextSegment( LLStyleConstSP style, S32 start, S32 e
 {
     mFontHeight = mStyle->getFont()->getLineHeight();
     mCanEdit = !mStyle->getDrawHighlightBg();
+    if (!mCanEdit)
+    {
+        // Emoji shouldn't split the segment with the mention.
+        mPermitsEmoji = false;
```
Comment (akleshchev) [inline indra/llui/lltextbase.cpp:3526]: That's probably valid for any special segment, be that a segment with special highligts, icons or a link.
