### PR TITLE
#5304 fix UI inconsistencies related to maturity setting in Legacy Se…

### LINKED ISSUE #5304: UI inconsistencies related to maturity setting in Legacy Search floater
### Description

There are two separate issues related to maturity setting in Legacy Search floater:

1. After login set maturity in Preferences>General to General
2. Open World>Legacy Search
3. Select 'Land Sales' tab

Actual result:  'Moderate' and 'Adult' checkbox are disabled. Changing maturity in Preferences won't enable it again.
Expected: All maturity checkboxes are enabled for Search, similar to other tabs. (Selecting 'M' or 'A' will be ignored, if you set 'General' in Preferences),

-

1. Open World>Legacy Search while maturity is set General, Moderate, Adult
2. Set maturity in Preferences>General to General (these first 2 steps are mostly to avoid the bug above)
3. For Places, Land Sales, Events, Classifieds tabs set maturity setting only to 'A'
4. In each of the tab try to Search anything 

Actual result: 
Land Sales, Classifieds - you get the search results according to your maturity settings in Preferences (General) 
Places, Events - you get 'Please select at least one type of content to search (General, Moderate, or Adult)' notification, although 'A' is actually selected

Expected: Search in the Places and Events tab should have similar behavior as Land Sales, Classifieds, so you'll get Search results, but adjusted to your maturity setting.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5304</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @maxim-productengine</code> (replace <code>20</code> with the amount, and <code>@maxim-productengine</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by maxim-productengine**
Land sale tab: Fix disabling checkbox once on opening Search floater
Events and Places tabs: ensure search results are shown when agent cannot access higher maturity content.
Update maturity search checkbox if maturity is changed in Preferences (similar to Events tab).

Retargeted https://github.com/secondlife/viewer/pull/5307

### CODE REVIEW

**Review by akleshchev — APPROVED** [review]

**Review by marchcat — APPROVED** [review]

File: indra/newview/llfloaterpreference.cpp [hunk 1]
```diff
@@ -1735,6 +1735,22 @@ void LLFloaterPreference::onChangeMaturity()
...
+        gSavedSettings.setBOOL("ShowMatureSims", false);
+        gSavedSettings.setBOOL("ShowMatureLand", false);
+        gSavedSettings.setBOOL("ShowMatureClassifieds", false);
+    }
+    if (!can_access_adult)
+    {
+        gSavedSettings.setBOOL("ShowAdultSims", false);
+        gSavedSettings.setBOOL("ShowAdultLand", false);
+        gSavedSettings.setBOOL("ShowAdultClassifieds", false);
+    }
```
Comment (akleshchev) [inline indra/newview/llfloaterpreference.cpp:1753]: Can there be any potential conflicts with previous version of the viewer? Like old viewer dropping values?

Comment (maxim-productengine) [reply indra/newview/llfloaterpreference.cpp:1753]: These debug settings were re-added with Legacy Search floater, so old viewer just use it,
