### PR TITLE
[#5155] Cleaned up unnecessary fake bool usage where appropriate

### LINKED ISSUE #5155: Cleanup fake bool usage where they are unnecessary or incorrect
PR: https://github.com/secondlife/viewer/pull/5156

There is a few places remaining in the viewer where fake bools (BOOL/FALSE/TRUE) are used where they aren't necessary and/or the signature of the function they are used in expects a regular bool.

There are uses of fake bools for pre-existing APIs such as WinAPI or gtk, which should be left untouched and not refactored to follow standards.

The fake bool used in the LL Havok lib- LLPathingLib::createPhysicsCapsuleRep should ideally be updated too, so then the fake bool usage of that function can be removed from the viewer side as well.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5155</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @Hecklezz</code> (replace <code>20</code> with the amount, and <code>@Hecklezz</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by Hecklezz**
Issue: https://github.com/secondlife/viewer/issues/5155

~~**Note:** Probably best to wait for Rye's other PR to be merged first and then I'll rebase this one, as there will be a couple conflicts with him deleting source files- https://github.com/secondlife/viewer/pull/5153~~ _Merged_

Simply cleans up usages of fake bools where a regular bool is more appropriate, or where function declarations expect a regular bool but a fake bool was used instead.

Fake bool usages in existing APIs such as WinAPI or gtk and others were left untouched as to follow the standards of those libraries.

I also didn't update the fake bool usage for LLPathingLib::createPhysicsCapsuleRep because this would require a change in the LL Havok library to avoid any implicit conversions.

### CODE REVIEW

File: indra/newview/lllookshistorypanel.h
Comment (Ansariel) [inline indra/newview/lllookshistorypanel.h:1]: This header seems to be unused.

File: indra/newview/llpanelimcontrolpanel.h
Comment (Ansariel) [inline indra/newview/llpanelimcontrolpanel.h:1]: This header seems to be unused, too.

File: indra/llcommon/StackWalker.cpp [hunk 1]
```diff
@@ -904,7 +904,7 @@ bool StackWalker::LoadModules()
     SetLastError(ERROR_DLL_INIT_FAILED);
     return false;
   }
-  if (m_modulesLoaded != FALSE)
+  if (m_modulesLoaded != false)
```
Comment (Ansariel) [inline indra/llcommon/StackWalker.cpp]:
```suggestion
  if (!m_modulesLoaded)
```

File: indra/newview/lltoolview.cpp
Comment (Ansariel) [inline indra/newview/lltoolview.cpp:1]: This file also seems to be unused.

File: indra/llcommon/StackWalker.cpp (hunk 1 above)
Comment (Hecklezz) [reply indra/llcommon/StackWalker.cpp]: I believe you meant-
if (m_modulesLoaded)

:)

**Comment by Hecklezz** [comment]
Dealing with the unused files if they are wanted to be removed is probably best done in another PR as it is out of scope of the current issue. No harm in fixing the fake bools in them in this one though even if unused.

**Comment by akleshchev** [comment]
> Probably best to wait for Rye's other PR

Pulled that one in, looks like there are conflicts in this PR now.

**Comment by Hecklezz** [comment]
> > Probably best to wait for Rye's other PR
> 
> Pulled that one in, looks like there are conflicts in this PR now.

All done, should be no conflicts now.

**Review by akleshchev — APPROVED** [review]
