### PR TITLE
#5607 workaround fix for the web content being black after resizing

### LINKED ISSUE #5607: Login page content window can go black for long period of time while resizing viewer window mainly on Events and status tabs of login page
### Environment

Second Life Project Flat UI 26.2.0.23875064053 (64bit)
Release Notes

CPU: Apple M1 (2400 MHz)
Memory: 16384 MB
OS Version: macOS 26.3.1 Darwin 25.3.0 Darwin Kernel Version 25.3.0: Wed Jan 28 20:53:31 PST 2026; root:xnu-12377.91.3~2/RELEASE_ARM64_T8103 arm64
Graphics Card Vendor: Apple
Graphics Card: Apple M1

OpenGL Version: 4.1 Metal - 90.5

Window size: 2554x1628
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 12124MB
Disk cache: Max size 2150.4 MB (30.8% used)
HiDPI display mode: true

J2C Decoder Version: KDU v8.4.1
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.24.2 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.24.0.202510081737
  CEF: 139.0.40+g465474a+chromium-139.0.7258.139
  Chromium: 139.0.7258.139
LibVLC Version: 3.0.21
Voice Server Version:  

April 02 2026 08:08:40

### Description

When launching the viewer with the new login page on both mac and windows, mainly when viewing the Events and Status tabs, when resizing the viewer window size it is possible to get in a state where the content goes black during resize and either never updates or updates after 20-30 seconds.

### Reproduction steps

1. Launch viewer from https://github.com/secondlife/viewer/releases/tag/Second_Life_Project%231c3158a7-FlatUI
2. On the login page select the events tab
3. Resize the viewer window, sometimes it triggers on the first resize sometimes you may need to resize back and forth a couple of times to trigger
4. Observe that it is possible to have the content go black for extended period of time.  
5. Video capture of issue occurring: https://gyazo.com/290bb04d2de24210ac93c8070322f47d
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5607</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @kurtlinden</code> (replace <code>20</code> with the amount, and <code>@kurtlinden</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by maxim-productengine**
Temporary workaround until the root cause in Dullahan (?) is not fixed.

### CODE REVIEW

**Review by marchcat — APPROVED** [review]

**Review by akleshchev — APPROVED** [review]

File: indra/newview/llpanellogin.cpp [hunk 1]
```diff
@@ -1383,3 +1394,19 @@ void LLPanelLogin::collapseGridPanel(bool collapse)
...
+{
+    LLPanel::draw();
+
+    // Workaround for the black screen issue (see #5607)
+    // Should be removed after the proper fix for resizing is implemented
+    if (mForceRefresh && mForceRefreshTimer.hasExpired())
+    {
+        if (mWebBrowser->getMediaPlugin())
+        {
+            mWebBrowser->getMediaPlugin()->forceRenderRefresh();
```
Comment (akleshchev) [inline indra/newview/llpanellogin.cpp:1408]: Might be better to have this in LLPluginClassMedia::idle for a general solution instead of specific to a single panel.

Comment (maxim-productengine) [reply indra/newview/llpanellogin.cpp:1408]: I would prefer a proper fix (https://github.com/secondlife/viewer/issues/4712) instead of this workaround. 
For now, let's use it just for Login screen. If there are complications with dullahan/cef, I'll use your suggestion later.
