### PR TITLE
Media first click interact friend check fix

### LINKED ISSUE #4414: MediaFirstClickInteract should work with the Landowner objects Preference.
### Environment

Second Life Release 7.2.0.16356654553 (64bit)
Release Notes

You are at 23.5, 52.8, 37.3 in Danger! Danger! located at simhost-03e3afe4338435f44.agni
SLURL: http://maps.secondlife.com/secondlife/Danger%21%20Danger%21/24/53/37
(global coordinates 261,144.0, 249,653.0, 37.3)
Second Life Server 2025-04-24.14648572313
Release Notes

CPU: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (3491.91 MHz)
Memory: 32610 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.6093)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce GTX 1080/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.6590
OpenGL Version: 4.6.0 NVIDIA 565.90

Window size: 1757x1385
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 3000kbit/s
LOD factor: 1.375
Render quality: 3
Texture memory: 8192MB
Disk cache: Max size 1638.4 MB (13.2% used)

J2C Decoder Version: KDU v7.10.4
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.24.2 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.14.0.202408091639
  CEF: 118.4.1+g3dd6078+chromium-118.0.5993.54
  Chromium: 118.0.5993.54
LibVLC Version: 3.0.21
Voice Server Version: Vivox 4.10.0000.32327.5fc3fe7c.5942f08

Packets Lost: 0/1,969 (0.0%)
July 22 2025 12:39:59

### Description

MediaFirstClickInteract = 31 should work with the Landowner objects option as set in the Preferences panel

### Reproduction steps

1. User A: Create a prim and put the following script in it
```
default {
    state_entry() {
        llSetLinkMedia( LINK_THIS, 0, [
            PRIM_MEDIA_CURRENT_URL, "http://lecs-viewer-web-components.s3.amazonaws.com/v3.0/agni/avatars.html",
            PRIM_MEDIA_HOME_URL, "http://lecs-viewer-web-components.s3.amazonaws.com/v3.0/agni/avatars.html",
            PRIM_MEDIA_FIRST_CLICK_INTERACT, TRUE,
            PRIM_MEDIA_AUTO_PLAY, TRUE,
            PRIM_MEDIA_CONTROLS, PRIM_MEDIA_CONTROLS_MINI
        ] );
    }
}
```
2. Place the prim on a parcel you own.
3. Log in with a User B.
4. Set Preferences > Sound & Media > Media first-interact: Landowner objects. (This sets debug setting MediaFirstClickInteract to 31.)
5. Stand on User A's parcel and look a the media.
6. Without clicking the MOAP object, move your cursor over it and verify the webpage tracks the hover.

Observed: The media is not interacting. 

Expected: The MOAP should track the cursor hover.

Workaround: Set Debug Settings > MediaFirstClickInteract to 16. The MOAP now tracks the cursor.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #4414</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @Dan-Linden</code> (replace <code>20</code> with the amount, and <code>@Dan-Linden</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by DarlCat**
## Description

This PR fixes an error with how friendship status was handled for media first click interact purposes. It caused proceeding checks to never be run in the event it itself was run and failed.

## Related Issues

Issue Link: closes #4414

### CODE REVIEW

**Review by akleshchev — APPROVED** [review]

File: indra/newview/lltoolpie.cpp [hunk 1]
```diff
@@ -1572,8 +1572,11 @@ bool LLToolPie::shouldAllowFirstMediaInteraction(const LLPickInfo& pick, bool mo
     // Check if the object is owned by a friend of the agent
     if(FirstClickPref & MEDIA_FIRST_CLICK_FRIEND)
     {
-        LL_DEBUGS_ONCE() << "FirstClickPref & MEDIA_FIRST_CLICK_FRIEND. id: " << owner_id << LL_ENDL;
-        return LLAvatarTracker::instance().isBuddy(owner_id);
+        if(LLAvatarTracker::instance().isBuddy(owner_id))
+        {
+            LL_DEBUGS_ONCE() << "FirstClickPref & MEDIA_FIRST_CLICK_FRIEND. id: " << owner_id << LL_ENDL;
```
Comment (akleshchev) [inline indra/newview/lltoolpie.cpp:1577]: 'debugs' and 'infos' options are the most unsefull when they have a tag, so that instead of having to toggle 'debug' for multiple files individually, we can use log control to, as an example, turn on "MediaFirstClick' only and it will start working across multiple files.
