### PR TITLE
#4656 Don't scroll to a child that is already in view and can not fit

### LINKED ISSUE #2618: Roles and Members tab is a mess
### Environment

Second Life Release 7.1.9.10515727195 (64bit)

### Description

Lots of unused space, weird jumping, spacing. banned members is the worst off.

### Reproduction steps

1. Create or edit a group
2. Add a large list of banned residents.
3. Switch tabs away and to banned (view will jump oddly, hiding tabs)
4. Try scrolling ban list (scroll goes off screen)
5. Extra free space below tabs list (either whole list should fit on screen or there should be no free space)
6. Free, potentially useles space in other tabs.

Example: space after the ban list
Image

### PR DESCRIPTION
**Pull request by akleshchev**
Basically, if a 700-high child already takes majority of a 400-high parent, don't scroll to the bottom. Scroll in every other case.

### CODE REVIEW

**Review by marchcat — APPROVED** [review]

File: indra/llui/llaccordionctrltab.cpp [hunk 1]
```diff
@@ -479,7 +479,34 @@ void LLAccordionCtrlTab::onUpdateScrollToChild(const LLUICtrl *cntrl)
...
+            }
+            else if (acc_rect.getHeight() >= rect.getHeight())
+            {
+                // Content can be displayed fully, but only partially in view
+                needs_to_scroll = true;
+            }
+            else if (acc_rect.mTop <= rect.mTop || acc_rect.mBottom >= rect.mBottom)
+            {
+                // Intersects, but too big to be displayed fully
+                S32 covered_width = acc_rect.mTop > rect.mTop ? rect.mTop - acc_rect.mBottom : acc_rect.mTop - rect.mBottom;
```
Comment (maxim-productengine) [inline indra/llui/llaccordionctrltab.cpp]: Probably, it should be 'covered_height'?

**Review by maxim-productengine — APPROVED** [review]

File: indra/llui/llaccordionctrltab.cpp [hunk 2]
```diff
@@ -479,7 +479,34 @@ void LLAccordionCtrlTab::onUpdateScrollToChild(const LLUICtrl *cntrl)
...
+                constexpr F32 coevered_ratio = 0.7f;
```
Comment (maxim-productengine) [inline indra/llui/llaccordionctrltab.cpp]: 'coevered' typo

File: indra/llui/llaccordionctrltab.cpp (hunk 1 above)
Comment (akleshchev) [reply indra/llui/llaccordionctrltab.cpp]: Yeah, thanks, fixed!
