### PR TITLE
#4931 Fix name cache callbacks not having connections

### LINKED ISSUE #4931: BugSplat Crash: SecondLifeViewer!LLUUID::operator==(941)
## BugSplat Crash Group 100329
[View Report Group](https://app.bugsplat.com/v2/group?stackKeyId=100329&database=SecondLife_Viewer_2018)
[View Report Details](https://app.bugsplat.com/v2/crash?id=1677730&database=SecondLife_Viewer_2018)
[View Report Attachments](https://app.bugsplat.com/v2/crash?id=1677730&database=SecondLife_Viewer_2018#attachments)

**Application:** Second Life Release
**Version:** 7.2.3.18887079901
**Error Code:** c0000005 Access violation

**Callstack:**
<table><tr><th>Function</th><th>File</th></tr><tr><td>SecondLifeViewer!LLUUID::operator==</td><td>C:/a/viewer/viewer/indra/llcommon/lluuid.cpp(941)</td></tr><tr><td>SecondLifeViewer!LLConversationLogListItem::onIMFloaterShown</td><td>C:/a/viewer/viewer/indra/newview/llconversationloglistitem.cpp(151)</td></tr><tr><td>SecondLifeViewer!boost::function_n<void,LLSD &>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/function/function_template.hpp(789)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/variadic_slot_invoker.hpp(105)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/variadic_slot_invoker.hpp(90)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLSD &>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/variadic_slot_invoker.hpp(133)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLSD &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLSD &),boost::function<void __cdecl(LLSD &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLSD &),boost::function<void __cdecl(LLSD &)> >,boost::signals2::mutex> >::dereference</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/slot_call_iterator.hpp(108)</td></tr><tr><td>SecondLifeViewer!boost::iterators::iterator_core_access::dereference</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/iterator/iterator_facade.hpp(631)</td></tr><tr><td>SecondLifeViewer!boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLSD &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLSD &),boost::function<void __cdecl(LLSD &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLSD &),boost::function<void __cdecl(LLSD &)> >,boost::signals2::mutex> >,boost::signals2::detail::void_type,boost::iterators::single_pass_traversal_tag,boost::signals2::detail::void_type &,__int64,0,0>::operator*</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/iterator/iterator_facade.hpp(737)</td></tr><tr><td>SecondLifeViewer!boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLSD &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLSD &),boost::function<void __cdecl(LLSD &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLSD &),boost::function<void __cdecl(LLSD &)> >,boost::signals2::mutex> > ></td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/optional_last_value.hpp(58)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::combiner_invoker<void>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/result_type_wrapper.hpp(64)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::signal_impl<void __cdecl(LLUUID const &),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(LLUUID const &)>,boost::function<void __cdecl(boost::signals2::connection const &,LLUUID const &)>,boost::signals2::mutex>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/signal_template.hpp(246)</td></tr><tr><td>SecondLifeViewer!boost::signals2::signal<void __cdecl(LLUUID const &),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(LLUUID const &)>,boost::function<void __cdecl(boost::signals2::connection const &,LLUUID const &)>,boost::signals2::mutex>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/signal_template.hpp(733)</td></tr><tr><td>SecondLifeViewer!LLFloaterIMSession::setVisible</td><td>C:/a/viewer/viewer/indra/newview/llfloaterimsession.cpp(717)</td></tr><tr><td>SecondLifeViewer!LLMultiFloater::setVisible</td><td>C:/a/viewer/viewer/indra/llui/llmultifloater.cpp(345)</td></tr><tr><td>SecondLifeViewer!LLFloaterIMContainer::setVisible</td><td>C:/a/viewer/viewer/indra/newview/llfloaterimcontainer.cpp(823)</td></tr><tr><td>SecondLifeViewer!LLFloater::setVisibleAndFrontmost</td><td>C:/a/viewer/viewer/indra/llui/llfloater.cpp(1783)</td></tr><tr><td>SecondLifeViewer!LLFloaterIMContainer::setVisibleAndFrontmost</td><td>C:/a/viewer/viewer/indra/newview/llfloaterimcontainer.cpp(851)</td></tr><tr><td>SecondLifeViewer!LLFloaterIMContainer::showConversation</td><td>C:/a/viewer/viewer/indra/newview/llfloaterimcontainer.cpp(1694)</td></tr><tr><td>SecondLifeViewer!on_avatar_name_cache_start_im</td><td>C:/a/viewer/viewer/indra/newview/llavataractions.cpp(215)</td></tr><tr><td>SecondLifeViewer!boost::function_n<void,LLVector3 const &,LLVector3d const &>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/function/function_template.hpp(789)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/variadic_slot_invoker.hpp(105)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/variadic_slot_invoker.hpp(90)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLVector3 const &,LLVector3d const &>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/variadic_slot_invoker.hpp(133)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLVector3 const &,LLVector3d const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLVector3 const &,LLVector3d const &),boost::function<void __cdecl(LLVector3 const &,LLVector3d const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLVector3 const &,LLVector3d const &),boost::function<void __cdecl(LLVector3 const &,LLVector3d const &)> >,boost::signals2::mutex> >::dereference</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/slot_call_iterator.hpp(108)</td></tr><tr><td>SecondLifeViewer!boost::iterators::iterator_core_access::dereference</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/iterator/iterator_facade.hpp(631)</td></tr><tr><td>SecondLifeViewer!boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLVector3 const &,LLVector3d const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLVector3 const &,LLVector3d const &),boost::function<void __cdecl(LLVector3 const &,LLVector3d const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLVector3 const &,LLVector3d const &),boost::function<void __cdecl(LLVector3 const &,LLVector3d const &)> >,boost::signals2::mutex> >,boost::signals2::detail::void_type,boost::iterators::single_pass_traversal_tag,boost::signals2::detail::void_type &,__int64,0,0>::operator*</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/iterator/iterator_facade.hpp(737)</td></tr><tr><td>SecondLifeViewer!boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLVector3 const &,LLVector3d const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLVector3 const &,LLVector3d const &),boost::function<void __cdecl(LLVector3 const &,LLVector3d const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLVector3 const &,LLVector3d const &),boost::function<void __cdecl(LLVector3 const &,LLVector3d const &)> >,boost::signals2::mutex> > ></td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/optional_last_value.hpp(58)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::combiner_invoker<void>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/result_type_wrapper.hpp(64)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::signal_impl<void __cdecl(LLUUID const &,LLAvatarName const &),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(LLUUID const &,LLAvatarName const &)>,boost::function<void __cdecl(boost::signals2::connection const &,LLUUID const &,LLAvatarName const &)>,boost::signals2::mutex>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/signal_template.hpp(246)</td></tr><tr><td>SecondLifeViewer!boost::signals2::signal<void __cdecl(LLUUID const &,LLAvatarName const &),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(LLUUID const &,LLAvatarName const &)>,boost::function<void __cdecl(boost::signals2::connection const &,LLUUID const &,LLAvatarName const &)>,boost::signals2::mutex>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/signal_template.hpp(733)</td></tr><tr><td>SecondLifeViewer!LLAvatarNameCache::fireSignal</td><td>C:/a/viewer/viewer/indra/llmessage/llavatarnamecache.cpp(669)</td></tr><tr><td>SecondLifeViewer!LLAvatarNameCache::getNameCallback</td><td>C:/a/viewer/viewer/indra/llmessage/llavatarnamecache.cpp(693)</td></tr><tr><td>SecondLifeViewer!LLAvatarNameCache::get</td><td>C:/a/viewer/viewer/indra/llmessage/llavatarnamecache.cpp(675)</td></tr><tr><td>SecondLifeViewer!LLAvatarActions::startIM</td><td>C:/a/viewer/viewer/indra/newview/llavataractions.cpp(224)</td></tr><tr><td>SecondLifeViewer!LLAvatarSendIM::handleEvent</td><td>C:/a/viewer/viewer/indra/newview/llviewermenu.cpp(7772)</td></tr><tr><td>SecondLifeViewer!boost::_mfi::mf<bool (__cdecl LLControlCache<bool>::*)(LLSD const &),bool,LLControlCache<bool>,LLSD const &>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/bind/mem_fn.hpp(74)</td></tr><tr><td>SecondLifeViewer!boost::_bi::list<boost::_bi::value<LLControlCache<bool> *>,boost::arg<2> >::call_impl</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/bind/bind.hpp(182)</td></tr><tr><td>SecondLifeViewer!boost::_bi::list<boost::_bi::value<LLControlCache<bool> *>,boost::arg<2> >::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/bind/bind.hpp(208)</td></tr><tr><td>SecondLifeViewer!boost::_bi::bind_t<boost::_bi::unspecified,boost::_mfi::mf<bool (__cdecl LLControlCache<bool>::*)(LLSD const &),bool,LLControlCache<bool>,LLSD const &>,boost::_bi::list<boost::_bi::value<LLControlCache<bool> *>,boost::arg<2> > >::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/bind/bind.hpp(321)</td></tr><tr><td>SecondLifeViewer!boost::detail::function::void_function_obj_invoker<boost::_bi::bind_t<boost::_bi::unspecified,boost::_mfi::mf<bool (__cdecl LLControlCache<bool>::*)(LLSD const &),bool,LLControlCache<bool>,LLSD const &>,boost::_bi::list<boost::_bi::value<LLControlCache<bool> *>,boost::arg<2> > >,void,LLControlVariable *,LLSD const &,LLSD const &>::invoke</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/function/function_template.hpp(101)</td></tr><tr><td>SecondLifeViewer!boost::function_n<void,LLUICtrl *,LLSD const &>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/function/function_template.hpp(789)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::m_invoke</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/variadic_slot_invoker.hpp(105)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::call_with_tuple_args<boost::signals2::detail::void_type>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/variadic_slot_invoker.hpp(90)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLUICtrl *,LLSD const &>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/variadic_slot_invoker.hpp(133)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLUICtrl *,LLSD const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLUICtrl *,LLSD const &),boost::function<void __cdecl(LLUICtrl *,LLSD const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLUICtrl *,LLSD const &),boost::function<void __cdecl(LLUICtrl *,LLSD const &)> >,boost::signals2::mutex> >::dereference</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/slot_call_iterator.hpp(108)</td></tr><tr><td>SecondLifeViewer!boost::iterators::iterator_core_access::dereference</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/iterator/iterator_facade.hpp(631)</td></tr><tr><td>SecondLifeViewer!boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLUICtrl *,LLSD const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLUICtrl *,LLSD const &),boost::function<void __cdecl(LLUICtrl *,LLSD const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLUICtrl *,LLSD const &),boost::function<void __cdecl(LLUICtrl *,LLSD const &)> >,boost::signals2::mutex> >,boost::signals2::detail::void_type,boost::iterators::single_pass_traversal_tag,boost::signals2::detail::void_type &,__int64,0,0>::operator*</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/iterator/iterator_facade.hpp(737)</td></tr><tr><td>SecondLifeViewer!boost::signals2::optional_last_value<void>::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<boost::signals2::detail::void_type,LLUICtrl *,LLSD const &>,std::_List_iterator<std::_List_val<std::_List_simple_types<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLUICtrl *,LLSD const &),boost::function<void __cdecl(LLUICtrl *,LLSD const &)> >,boost::signals2::mutex> > > > >,boost::signals2::detail::connection_body<std::pair<enum boost::signals2::detail::slot_meta_group,boost::optional<int> >,boost::signals2::slot<void __cdecl(LLUICtrl *,LLSD const &),boost::function<void __cdecl(LLUICtrl *,LLSD const &)> >,boost::signals2::mutex> > ></td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/optional_last_value.hpp(58)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::combiner_invoker<void>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/result_type_wrapper.hpp(64)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::signal_impl<void __cdecl(LLUICtrl *,LLSD const &),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(LLUICtrl *,LLSD const &)>,boost::function<void __cdecl(boost::signals2::connection const &,LLUICtrl *,LLSD const &)>,boost::signals2::mutex>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/signal_template.hpp(246)</td></tr><tr><td>SecondLifeViewer!boost::signals2::signal<void __cdecl(LLUICtrl *,LLSD const &),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(LLUICtrl *,LLSD const &)>,boost::function<void __cdecl(boost::signals2::connection const &,LLUICtrl *,LLSD const &)>,boost::signals2::mutex>::operator()</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/signal_template.hpp(733)</td></tr><tr><td>SecondLifeViewer!LLUICtrl::onCommit</td><td>C:/a/viewer/viewer/indra/llui/lluictrl.cpp(437)</td></tr><tr><td>SecondLifeViewer!LLMenuItemGL::handleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/llmenugl.cpp(462)</td></tr><tr><td>SecondLifeViewer!LLView::childrenHandleMouseEvent<bool (__cdecl LLView::*)(int,int,unsigned int),unsigned int></td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(767)</td></tr><tr><td>SecondLifeViewer!LLView::childrenHandleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(1207)</td></tr><tr><td>SecondLifeViewer!LLView::handleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(1111)</td></tr><tr><td>SecondLifeViewer!LLUICtrl::handleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/lluictrl.cpp(370)</td></tr><tr><td>SecondLifeViewer!LLView::childrenHandleMouseEvent<bool (__cdecl LLView::*)(int,int,unsigned int),unsigned int></td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(767)</td></tr><tr><td>SecondLifeViewer!LLView::childrenHandleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(1207)</td></tr><tr><td>SecondLifeViewer!LLView::handleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(1111)</td></tr><tr><td>SecondLifeViewer!LLUICtrl::handleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/lluictrl.cpp(370)</td></tr><tr><td>SecondLifeViewer!LLView::childrenHandleMouseEvent<bool (__cdecl LLView::*)(int,int,unsigned int),unsigned int></td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(767)</td></tr><tr><td>SecondLifeViewer!LLView::childrenHandleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(1207)</td></tr><tr><td>SecondLifeViewer!LLView::handleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(1111)</td></tr><tr><td>SecondLifeViewer!LLUICtrl::handleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/lluictrl.cpp(370)</td></tr><tr><td>SecondLifeViewer!LLView::childrenHandleMouseEvent<bool (__cdecl LLView::*)(int,int,unsigned int),unsigned int></td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(767)</td></tr><tr><td>SecondLifeViewer!LLView::childrenHandleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(1207)</td></tr><tr><td>SecondLifeViewer!LLView::handleMouseUp</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(1111)</td></tr><tr><td>SecondLifeViewer!LLMouseHandler::handleAnyMouseClick</td><td>C:/a/viewer/viewer/indra/llwindow/llmousehandler.cpp(53)</td></tr><tr><td>SecondLifeViewer!LLViewerWindow::handleAnyMouseClick</td><td>C:/a/viewer/viewer/indra/newview/llviewerwindow.cpp(1120)</td></tr><tr><td>SecondLifeViewer!LLViewerInput::handleMouse</td><td>C:/a/viewer/viewer/indra/newview/llviewerinput.cpp(1619)</td></tr><tr><td>SecondLifeViewer!LLViewerWindow::handleMouseUp</td><td>C:/a/viewer/viewer/indra/newview/llviewerwindow.cpp(1204)</td></tr><tr><td>SecondLifeViewer!`LLWindowWin32::mainWindowProc'::`98'::<lambda_19>::operator()</td><td>C:/a/viewer/viewer/indra/llwindow/llwindowwin32.cpp(2747)</td></tr><tr><td>SecondLifeViewer!std::_Func_class<void>::operator()</td><td>C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207/include/functional(926)</td></tr><tr><td>SecondLifeViewer!LLWindowWin32::gatherInput</td><td>C:/a/viewer/viewer/indra/llwindow/llwindowwin32.cpp(2272)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::doFrame</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1421)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::frame</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1337)</td></tr><tr><td>SecondLifeViewer!wWinMain</td><td>C:/a/viewer/viewer/indra/newview/llappviewerwin32.cpp(516)</td></tr><tr><td>SecondLifeViewer!invoke_main</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(118)</td></tr><tr><td>SecondLifeViewer!__scrt_common_main_seh</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(288)</td></tr><tr><td>kernel32!BaseThreadInitThunk</td><td> - </td></tr><tr><td>ntdll!RtlUserThreadStart</td><td> - </td></tr></table>
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #4931</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @sl-service-account</code> (replace <code>20</code> with the amount, and <code>@sl-service-account</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by akleshchev**
Looks like crash happened on LLConversationLogListItem::onIMFloaterShown, but there is not enough details, so for now switched to lambda instead of boost.
Added missing callback connections in a bunch of places.

### CODE REVIEW

File: indra/newview/llfloaterexperiences.cpp [hunk 1]
```diff
@@ -171,7 +171,7 @@ void LLFloaterExperiences::onOpen( const LLSD& key )
             refreshContents();
             return;
         }
-        region->setCapabilitiesReceivedCallback(boost::bind(&LLFloaterExperiences::refreshContents, this));
+        mCapsReceivedConnection = region->setCapabilitiesReceivedCallback(boost::bind(&LLFloaterExperiences::refreshContents, this));
```
Comment (Ansariel) [inline indra/newview/llfloaterexperiences.cpp:174]: Not disconnecting the signal when closing the floater?

Comment (akleshchev) [reply indra/newview/llfloaterexperiences.cpp:174]: You are right, I should.

Comment (Ansariel) [reply indra/newview/llfloaterexperiences.cpp:174]: Seems to be everywhere in this PR - or you could try to use scoped_connection that disconnects automatically when getting destroyed or going out of scope.

Comment (akleshchev) [reply indra/newview/llfloaterexperiences.cpp:174]: Thanks. I was sure that I copied a scoped one...

**Review by marchcat — APPROVED** [review]

**Review by maxim-productengine — APPROVED** [review]
