### PR TITLE
[#5665] Fix experiences search and new classifieds content rating labels showing incorrectly

### LINKED ISSUE #5665: Experiences search and new Classifieds content rating combo boxes show the incorrect initial label
### Environment

Second Life Release 26.1.1.23806384790 (64bit)
<details>
<summary>Rest of Environment-</summary>
Release Notes

CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (3600.03 MHz)
Memory: 16302 MB
OS Version: Microsoft Windows 10 64-bit (Build 19045.7058)
Graphics Card Vendor: NVIDIA Corporation
Graphics Card: NVIDIA GeForce RTX 2080/PCIe/SSE2

Windows Graphics Driver Version: 32.0.15.8115
OpenGL Version: 4.6.0 NVIDIA 581.15

Window size: 1276x911
Font Size Adjustment: 96pt
UI Scaling: 1
Draw distance: 128m
Bandwidth: 10000kbit/s
LOD factor: 1.5
Render quality: 4
Texture memory: 8192MB
Disk cache: Max size 11468.8 MB (8.6% used)

J2C Decoder Version: KDU v8.4.1
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.24.2 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.24.0.202510081738
  CEF: 139.0.40+g465474a+chromium-139.0.7258.139
  Chromium: 139.0.7258.139
LibVLC Version: 3.0.21
Voice Server Version:  

April 17 2026 03:14:52
</details>

### Description

PR with potential fix: https://github.com/secondlife/viewer/pull/5666

Right now both the experiences search and creating classifieds content rating icons_combo_box show the incorrect initial label, and only correct themselves when you choose an option in the combo box.

What you expect to happen:
Show the correct initial label for the maturity rating in these two floaters.

<details>
<summary>Screenshots of the issue-</summary>

Image

Image

</details>

### Reproduction steps

Experiences:
1. Top Menu->Me->Experiences...
2. Click Search tab
3. Observe the content rating showing the incorrect label

Classifieds:
1. Top Menu->Me->Profile...
2. Click Classifieds tab
3. Click New...
4. Scroll down and observe the content type showing the incorrect label
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5665</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @Hecklezz</code> (replace <code>20</code> with the amount, and <code>@Hecklezz</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by Hecklezz**
Issue: https://github.com/secondlife/viewer/issues/5665

Simply fixes the above issue by getting the correct selected label on combo boxes, so icons_combo_box display the correct initial label.

### CODE REVIEW

**Review by marchcat — APPROVED** [review]
Thank you!

File: indra/llui/llcombobox.cpp [hunk 1]
```diff
@@ -521,7 +521,7 @@ bool LLComboBox::setCurrentByIndex(S32 index)
         if (item->getEnabled())
         {
             mList->selectItem(item, -1, true);
-            LLSD::String label = item->getColumn(0)->getValue().asString();
+            LLSD::String label = getSelectedItemLabel();
```
Comment (akleshchev) [inline indra/llui/llcombobox.cpp:524]: What's the difference?

getSelectedItemLabel does the following:
```
    item = mList->getFirstSelected(); // we just selected this item
    LLScrollListCell* cell = item->getColumn(0);
    return cell->getValue().asString();
```

**Review by akleshchev — APPROVED** [review]

File: indra/llui/llcombobox.cpp (hunk 1 above)
Comment (Hecklezz) [reply indra/llui/llcombobox.cpp:524]: The difference is the column index it uses is different. LLIconsComboBox::getSelectedItemLabel uses mLabelColumnIndex instead of 0 when calling LLComboBox::getSelectedItemLabel. Which actually isn't column 0, and therefore ends up getting a different cell from the item.

Here is the label string of both ways, and in this case, mLabelColumnIndex was 1 and not 0-

image
