### PR TITLE
#5497 Handle a case of missing files in conversation view

### LINKED ISSUE #5497: BugSplat Crash: SecondLifeViewer!LLView::getChild<LLPanel>(704)
## BugSplat Crash Group 105019
[View Report Group](https://app.bugsplat.com/v2/group?stackKeyId=105019&database=SecondLife_Viewer_2018)
[View Report Details](https://app.bugsplat.com/v2/crash?id=1716047&database=SecondLife_Viewer_2018)
[View Report Attachments](https://app.bugsplat.com/v2/crash?id=1716047&database=SecondLife_Viewer_2018#attachments)

**Application:** Second Life Release
**Version:** 26.1.0.22641522367
**Error Code:** c0000005 Access violation

**Callstack:**
<table><tr><th>Function</th><th>File</th></tr><tr><td>SecondLifeViewer!LLView::getChild<LLPanel></td><td>C:/a/viewer/viewer/indra/llui/llview.h(704)</td></tr><tr><td>SecondLifeViewer!LLConversationViewSession::postBuild</td><td>C:/a/viewer/viewer/indra/newview/llconversationview.cpp(215)</td></tr><tr><td>SecondLifeViewer!LLUICtrlFactory::create</td><td>C:/a/viewer/viewer/indra/llui/lluictrlfactory.h(142)</td></tr><tr><td>SecondLifeViewer!LLFloaterIMContainer::createConversationItemWidget</td><td>C:/a/viewer/viewer/indra/newview/llfloaterimcontainer.cpp(1994)</td></tr><tr><td>SecondLifeViewer!LLFloaterIMContainer::addConversationListItem</td><td>C:/a/viewer/viewer/indra/newview/llfloaterimcontainer.cpp(1869)</td></tr><tr><td>SecondLifeViewer!LLFloaterIMContainer::sessionVoiceOrIMStarted</td><td>C:/a/viewer/viewer/indra/newview/llfloaterimcontainer.cpp(132)</td></tr><tr><td>SecondLifeViewer!LLIMMgr::notifyObserverSessionAdded</td><td>C:/a/viewer/viewer/indra/newview/llimview.cpp(3838)</td></tr><tr><td>SecondLifeViewer!LLIMModel::newSession</td><td>C:/a/viewer/viewer/indra/newview/llimview.cpp(1594)</td></tr><tr><td>SecondLifeViewer!LLIMModel::newSession</td><td>C:/a/viewer/viewer/indra/newview/llimview.cpp(1604)</td></tr><tr><td>SecondLifeViewer!LLIMMgr::addMessage</td><td>C:/a/viewer/viewer/indra/newview/llimview.cpp(3213)</td></tr><tr><td>SecondLifeViewer!LLViewerChatterBoxInvitation::post</td><td>C:/a/viewer/viewer/indra/newview/llimview.cpp(4280)</td></tr><tr><td>SecondLifeViewer!LLMessageSystem::dispatch</td><td>C:/a/viewer/viewer/indra/llmessage/message.cpp(2076)</td></tr><tr><td>SecondLifeViewer!LLMessageSystem::dispatch</td><td>C:/a/viewer/viewer/indra/llmessage/message.cpp(2043)</td></tr><tr><td>SecondLifeViewer!LLEventPolling::Details::LLEventPollImpl::handleMessage</td><td>C:/a/viewer/viewer/indra/newview/lleventpoll.cpp(106)</td></tr><tr><td>SecondLifeViewer!LLEventPolling::Details::LLEventPollImpl::eventPollCoro::__l188::<lambda_1>::operator()</td><td>C:/a/viewer/viewer/indra/newview/lleventpoll.cpp(343)</td></tr><tr><td>SecondLifeViewer!std::invoke</td><td>C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207/include/type_traits(1670)</td></tr><tr><td>SecondLifeViewer!std::_Func_impl_no_alloc<`LLEventPolling::Details::LLEventPollImpl::eventPollCoro'::`188'::<lambda_1>,void>::_Do_call</td><td>C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207/include/functional(880)</td></tr><tr><td>SecondLifeViewer!std::_Func_class<void>::operator()</td><td>C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207/include/functional(926)</td></tr><tr><td>SecondLifeViewer!`anonymous namespace'::cpphandle</td><td>C:/a/viewer/viewer/indra/llcommon/workqueue.cpp(166)</td></tr><tr><td>SecondLifeViewer!`anonymous namespace'::sehandle</td><td>C:/a/viewer/viewer/indra/llcommon/workqueue.cpp(182)</td></tr><tr><td>SecondLifeViewer!LL::WorkQueueBase::callWork</td><td>C:/a/viewer/viewer/indra/llcommon/workqueue.cpp(201)</td></tr><tr><td>SecondLifeViewer!LL::WorkQueueBase::runUntil</td><td>C:/a/viewer/viewer/indra/llcommon/workqueue.cpp(111)</td></tr><tr><td>SecondLifeViewer!LL::WorkQueueBase::runFor</td><td>C:/a/viewer/viewer/indra/llcommon/workqueue.h(168)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::idle</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(4856)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::doFrame</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1483)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::frame</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1336)</td></tr><tr><td>SecondLifeViewer!wWinMain</td><td>C:/a/viewer/viewer/indra/newview/llappviewerwin32.cpp(523)</td></tr><tr><td>SecondLifeViewer!invoke_main</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(118)</td></tr><tr><td>SecondLifeViewer!__scrt_common_main_seh</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(288)</td></tr><tr><td>kernel32!BaseThreadInitThunk</td><td> - </td></tr><tr><td>ntdll!RtlUserThreadStart</td><td> - </td></tr></table>
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5497</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @sl-service-account</code> (replace <code>20</code> with the amount, and <code>@sl-service-account</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by akleshchev**
According to logs multiple files are missing/failed to parse, inform user about the need to reinstall

### CODE REVIEW

**Review by marchcat — APPROVED** [review]

File: indra/newview/llconversationview.cpp [hunk 1]
```diff
@@ -217,6 +217,12 @@ bool LLConversationViewSession::postBuild()
     LLFolderViewItem::postBuild();
 
     mItemPanel = LLUICtrlFactory::getInstance()->createFromFile<LLPanel>("panel_conversation_list_item.xml", NULL, LLPanel::child_registry_t::instance());
+
+    if (!mItemPanel)
```
Comment (maxim-productengine) [inline indra/newview/llconversationview.cpp:221]: It's a weird case. What is a chance this one file missing vs any other panel?

**Review by maxim-productengine — APPROVED** [review]

File: indra/newview/llconversationview.cpp (hunk 1 above)
Comment (akleshchev) [reply indra/newview/llconversationview.cpp:221]: There is a whole list of missing files/flaoters in the log, it's just this one that didn't create a dummy and didn't handle a fallback.
