### PR TITLE
#5228 crash at updateLoginButtons

### LINKED ISSUE #5228: BugSplat Crash: SecondLifeViewer!LLPanelLogin::updateLoginButtons(1199)
## BugSplat Crash Group 103922
[View Report Group](https://app.bugsplat.com/v2/group?stackKeyId=103922&database=SecondLife_Viewer_2018)
[View Report Details](https://app.bugsplat.com/v2/crash?id=1696155&database=SecondLife_Viewer_2018)
[View Report Attachments](https://app.bugsplat.com/v2/crash?id=1696155&database=SecondLife_Viewer_2018#attachments)

**Application:** Second Life Develop
**Version:** 2026.1.0.20736501739
**Error Code:** c0000005 Access violation

**Callstack:**
<table><tr><th>Function</th><th>File</th></tr><tr><td>SecondLifeViewer!LLPanelLogin::updateLoginButtons</td><td>C:/a/viewer/viewer/indra/newview/llpanellogin.cpp(1199)</td></tr><tr><td>SecondLifeViewer!LLPanelLogin::onUpdateStartSLURL</td><td>C:/a/viewer/viewer/indra/newview/llpanellogin.cpp(802)</td></tr><tr><td>SecondLifeViewer!LLPanelLogin::LLPanelLogin</td><td>C:/a/viewer/viewer/indra/newview/llpanellogin.cpp(299)</td></tr><tr><td>SecondLifeViewer!LLPanelLogin::show</td><td>C:/a/viewer/viewer/indra/newview/llpanellogin.cpp(517)</td></tr><tr><td>SecondLifeViewer!login_show</td><td>C:/a/viewer/viewer/indra/newview/llstartup.cpp(2543)</td></tr><tr><td>SecondLifeViewer!idle_startup</td><td>C:/a/viewer/viewer/indra/newview/llstartup.cpp(876)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::idle</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(4856)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::doFrame</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1479)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::frame</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1336)</td></tr><tr><td>SecondLifeViewer!wWinMain</td><td>C:/a/viewer/viewer/indra/newview/llappviewerwin32.cpp(523)</td></tr><tr><td>SecondLifeViewer!invoke_main</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(118)</td></tr><tr><td>SecondLifeViewer!__scrt_common_main_seh</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(288)</td></tr><tr><td>kernel32!BaseThreadInitThunk</td><td> - </td></tr><tr><td>ntdll!RtlUserThreadStart</td><td> - </td></tr></table>
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5228</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @sl-service-account</code> (replace <code>20</code> with the amount, and <code>@sl-service-account</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by maxim-productengine**
`mLoginBtn` was initialized too late, and `onUpdateStartSLURL` might be called before it which caused crash.

### CODE REVIEW

**Review by akleshchev — APPROVED** [review]

File: indra/newview/llpanellogin.cpp [hunk 1]
```diff
@@ -298,7 +300,6 @@ LLPanelLogin::LLPanelLogin(const LLRect &rect,
 
     childSetAction("connect_btn", onClickConnect, this);
 
-    mLoginBtn = getChild<LLButton>("connect_btn");
     setDefaultBtn(mLoginBtn);
```
Comment (akleshchev) [inline indra/newview/llpanellogin.cpp]: Perhaps move setDefaultBtn too? Also might be good to have a comment explaining that button is going to be needed soon.

**Review by marchcat — APPROVED** [review]

File: indra/newview/llpanellogin.cpp (hunk 1 above)
Comment (maxim-productengine) [reply indra/newview/llpanellogin.cpp]: Moved it, as you suggested,
