### PR TITLE
#5241 Crash at onIdleUpdateFavorites

### LINKED ISSUE #5241: BugSplat Crash: SecondLifeViewer!LLFolderViewFolder::onIdleUpdateFavorites(1887)
## BugSplat Crash Group 101750
[View Report Group](https://app.bugsplat.com/v2/group?stackKeyId=101750&database=SecondLife_Viewer_2018)
[View Report Details](https://app.bugsplat.com/v2/crash?id=1684572&database=SecondLife_Viewer_2018)
[View Report Attachments](https://app.bugsplat.com/v2/crash?id=1684572&database=SecondLife_Viewer_2018#attachments)

**Application:** Second Life Release
**Version:** 7.2.2.18475198968
**Error Code:** c0000005 Access violation

**Callstack:**
<table><tr><th>Function</th><th>File</th></tr><tr><td>SecondLifeViewer!LLFolderViewFolder::onIdleUpdateFavorites</td><td>C:/a/viewer/viewer/indra/llui/llfolderviewitem.cpp(1887)</td></tr><tr><td>SecondLifeViewer!LLCallbackList::callFunctions</td><td>C:/a/viewer/viewer/indra/llcommon/llcallbacklist.cpp(112)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::idle</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(4937)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::doFrame</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1479)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::frame</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1336)</td></tr><tr><td>SecondLifeViewer!wWinMain</td><td>C:/a/viewer/viewer/indra/newview/llappviewerwin32.cpp(507)</td></tr><tr><td>SecondLifeViewer!invoke_main</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(118)</td></tr><tr><td>SecondLifeViewer!__scrt_common_main_seh</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(288)</td></tr><tr><td>kernel32!BaseThreadInitThunk</td><td> - </td></tr><tr><td>ntdll!RtlUserThreadStart</td><td> - </td></tr></table>
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5241</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @sl-service-account</code> (replace <code>20</code> with the amount, and <code>@sl-service-account</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by maxim-productengine**
Crash seems to be happening after disconnecting, so simple check should be enough. (but we couldn't access gDisconnected from /llui, so moved it to llapp)

### CODE REVIEW

**Review by marchcat — APPROVED** [review]

File: indra/llcommon/llapp.h [hunk 1]
```diff
@@ -298,6 +301,8 @@ class LL_COMMON_API LLApp
 
     std::string mDumpPath;  //output path for google breakpad.  Dependency workaround.
 
+    static bool sDisconnected;
```
Comment (akleshchev) [inline indra/llcommon/llapp.h]: Why not do it like this?

bool isDisconnected() == 0;
bool LLAppViewer::isDisconnected()
{
    return gDisconnected;
}

Or not move gDisconnected elsewhere?

Comment (maxim-productengine) [reply indra/llcommon/llapp.h]: gDisconnected lives in llappviewer, so it can't be reached from non `newview` classes.
Yes, the idea was to get rid of gDisconnected later and to use only LLAppViewer::isDisconnected(). But I thought it would be too many changes not completely related to this crash.

Comment (maxim-productengine) [reply indra/llcommon/llapp.h]: On the other hand, we can just move gDisconnected  to llapp
