### PR TITLE
#5690 fix viewer trying to fetch group chat history for p2p IM

### LINKED ISSUE #5690: Viewer attempts to fetch group chat history for p2p IM conversations
### Environment

Second Life Release 26.1.1.23806384790 (64bit)
Release Notes

You are at 127.9, 127.9, 23.0 in webRTC1 located at simhost-07fe521507cacae37.aditi
SLURL: secondlife://Aditi/secondlife/webRTC1/128/128/23
(global coordinates 259968.0, 245376.0, 23.0)
WebRTC-Voice 2026-03-04.22660319648
Release Notes

CPU: Apple M1 Pro (2400 MHz)
Memory: 16384 MB
OS Version: macOS 26.3.1 Darwin 25.3.0 Darwin Kernel Version 25.3.0: Wed Jan 28 20:54:46 PST 2026; root:xnu-12377.91.3~2/RELEASE_ARM64_T6000 arm64
Graphics Card Vendor: Apple
Graphics Card: Apple M1 Pro

OpenGL Version: 4.1 Metal - 90.5

Window size: 943x674
Font Size Adjustment: 96pt
UI Scaling: 0.75
Draw distance: 320m
Bandwidth: 10000kbit/s
LOD factor: 1.125
Render quality: 1
Texture memory: 12124MB
Disk cache: Max size 2150.4 MB (45.8% used)
HiDPI display mode: 

J2C Decoder Version: KDU v8.4.1
Audio Driver Version: OpenAL, version 1.1 ALSOFT 1.24.2 / OpenAL Community / OpenAL Soft: OpenAL Soft
Dullahan: 1.24.0.202510081737
  CEF: 139.0.40+g465474a+chromium-139.0.7258.139
  Chromium: 139.0.7258.139
LibVLC Version: 3.0.21
Voice Server Version: Secondlife WebRTC Gateway 

Packets Lost: 0/20651 (0.0%)
April 21 2026 16:19:59

### Description

When on a webRTC region, the viewer attempts to fetch group chat history for the multiagentchat session that's automatically created to assist p2p voice calls.  This request always fails with a 403 'You cannot join chat' failure.   The request is only legitimate for non-p2p chat sessions (either ad hoc or for actual groups).

### Reproduction steps

1. Login to a webRTC region
2. Open an IM tab with any single avatar (either nearby, somebody on friends list, etc).
3. Look for errors in SecondLife.log

Actual results:
This error appears, apparently because the viewer tried to look up group-chat history for a non-group session:

```
2026-04-21T23:08:26Z INFO #IMVIEW# newview/llimview.cpp(3471) addSession : LLIMMgr::addSession, new session added, name = Litmoose, session id = 4990721f-f774-0e8e-375e-d8bde99addf5
2026-04-21T23:08:26Z WARNING #CoreHttp# llcorehttp/_httppolicy.cpp(403) stageAfterCompletion : HTTP request 0x708740018 failed after 0 retries.  Reason:  Forbidden (Http_403)
2026-04-21T23:08:26Z INFO # llmessage/llcorehttputil.cpp(275) onCompleted : Possible failure [Http_403] cannot POST url 'https://simhost-07fe521507cacae37.aditi.secondlife.io:12043/cap/98def6df-bd0c-a47d-a90d-07d34d621441' because Forbidden
2026-04-21T23:08:26Z INFO # llcommon/llsdserialize_xml.cpp(409) parse : LLSDXMLParser::Impl::parse: XML_STATUS_ERROR parsing:You cannot join chat
2026-04-21T23:08:26Z WARNING #ChatHistory# newview/llimview.cpp(656) chatterBoxHistoryCoro : 4990721f-f774-0e8e-375e-d8bde99addf5: Bad HTTP response in chatterBoxHistoryCoro, results: {'error_body':'You cannot join chat','headers':{},'message':'','status':i1,'success':0,'type':i403,'url':'https://simhost-07fe521507cacae37.aditi.secondlife.io:12043/cap/98def6df-bd0c-a47d-a90d-07d34d621441'}
```

Expected results:
The viewer should not make chatterBoxHistoryCoro requests for p2p chat sessions.   It should only do so when joining an ad hoc or group chat sessions, which might have queryable history.
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5690</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @maestrolinden</code> (replace <code>20</code> with the amount, and <code>@maestrolinden</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by maxim-productengine**
Don't attempt to fetch chat history for p2p sessions.

### CODE REVIEW

**Review by marchcat — APPROVED** [review]

**Review by akleshchev — APPROVED** [review]

File: indra/newview/llimview.cpp [hunk 1]
```diff
@@ -3253,8 +3253,8 @@ void LLIMMgr::addMessage(
                 return;
             }
 
-            // Fetch group chat history, enabled by default.
-            if (gSavedPerAccountSettings.getBOOL("FetchGroupChatHistory"))
```
Comment (akleshchev) [inline indra/newview/llimview.cpp:3257]: addMessage can be fairly frequent. Not the 'once per frame' frequent, but might be better to cache the setting.
