### PR TITLE
#5109 LLExperienceCache crashes on a coroutine

### LINKED ISSUE #5109: LLExperienceCache coroutine crashes
## BugSplat Crash Group 6320
[View Report Group](https://app.bugsplat.com/v2/group?stackKeyId=6320&database=SecondLife_Viewer_2018)
[View Report Details](https://app.bugsplat.com/v2/crash?id=1686752&database=SecondLife_Viewer_2018)
[View Report Attachments](https://app.bugsplat.com/v2/crash?id=1686752&database=SecondLife_Viewer_2018#attachments)

**Application:** Second Life Release
**Version:** 7.2.3.19375695301
**Error Code:** c0000005 Access violation

**Callstack:**
<table><tr><th>Function</th><th>File</th></tr><tr><td>SecondLifeViewer!boost::signals2::detail::unique_lock<boost::signals2::detail::connection_body_base>::{ctor}</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/unique_lock.hpp(29)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::garbage_collecting_lock<boost::signals2::detail::connection_body_base>::{ctor}</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/connection.hpp(44)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::connection_body_base::disconnect</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/connection.hpp(68)</td></tr><tr><td>SecondLifeViewer!boost::signals2::detail::signal_impl<void __cdecl(LLFocusableElement *),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(LLFocusableElement *)>,boost::function<void __cdecl(boost::signals2::connection const &,LLFocusableElement *)>,boost::signals2::mutex>::disconnect_all_slots</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/signal_template.hpp(205)</td></tr><tr><td>SecondLifeViewer!boost::signals2::signal<void __cdecl(LLFocusableElement *),boost::signals2::optional_last_value<void>,int,std::less<int>,boost::function<void __cdecl(LLFocusableElement *)>,boost::function<void __cdecl(boost::signals2::connection const &,LLFocusableElement *)>,boost::signals2::mutex>::disconnect_all_slots</td><td>C:/a/viewer/viewer/build-vc170-64/packages/include/boost/signals2/detail/signal_template.hpp(718)</td></tr><tr><td>SecondLifeViewer!`LLFocusableElement::~LLFocusableElement'::`2'::<lambda_1>::operator()</td><td>C:/a/viewer/viewer/indra/llui/llfocusmgr.cpp(80)</td></tr><tr><td>SecondLifeViewer!LLFocusableElement::~LLFocusableElement</td><td>C:/a/viewer/viewer/indra/llui/llfocusmgr.cpp(88)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(197)</td></tr><tr><td>SecondLifeViewer!LLAccordionCtrlTab::{dtor}</td><td>C:/a/viewer/viewer/indra/llui/llaccordionctrltab.cpp(400)</td></tr><tr><td>SecondLifeViewer!LLAccordionCtrlTab::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLAccordionCtrl::{dtor}</td><td>C:/a/viewer/viewer/indra/llui/llaccordionctrl.cpp(167)</td></tr><tr><td>SecondLifeViewer!LLAccordionCtrl::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLGalleryPanel::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLScrollContainer::{dtor}</td><td>C:/a/viewer/viewer/indra/llui/llscrollcontainer.cpp(156)</td></tr><tr><td>SecondLifeViewer!LLScrollContainer::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLPanelPlaceProfile::{dtor}</td><td>C:/a/viewer/viewer/indra/newview/llpanelplaceprofile.cpp(92)</td></tr><tr><td>SecondLifeViewer!LLPanelPlaceProfile::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLLayoutPanel::{dtor}</td><td>C:/a/viewer/viewer/indra/llui/lllayoutstack.cpp(90)</td></tr><tr><td>SecondLifeViewer!LLLayoutPanel::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLLayoutStack::{dtor}</td><td>C:/a/viewer/viewer/indra/llui/lllayoutstack.cpp(241)</td></tr><tr><td>SecondLifeViewer!LLLayoutStack::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLPanelPlaces::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLFloaterSidePanelContainer::{dtor}</td><td>C:/a/viewer/viewer/indra/newview/llfloatersidepanelcontainer.cpp(54)</td></tr><tr><td>SecondLifeViewer!LLFloaterSidePanelContainer::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLFloaterView::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLLayoutPanel::{dtor}</td><td>C:/a/viewer/viewer/indra/llui/lllayoutstack.cpp(90)</td></tr><tr><td>SecondLifeViewer!LLLayoutPanel::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLLayoutStack::{dtor}</td><td>C:/a/viewer/viewer/indra/llui/lllayoutstack.cpp(241)</td></tr><tr><td>SecondLifeViewer!LLLayoutStack::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLGalleryPanel::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLView::deleteAllChildren</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(588)</td></tr><tr><td>SecondLifeViewer!LLView::~LLView</td><td>C:/a/viewer/viewer/indra/llui/llview.cpp(185)</td></tr><tr><td>SecondLifeViewer!LLRootView::`scalar deleting destructor'</td><td> - </td></tr><tr><td>SecondLifeViewer!LLViewerWindow::shutdownViews</td><td>C:/a/viewer/viewer/indra/newview/llviewerwindow.cpp(2400)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::cleanup</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1862)</td></tr><tr><td>SecondLifeViewer!LLAppViewerWin32::cleanup</td><td>C:/a/viewer/viewer/indra/newview/llappviewerwin32.cpp(813)</td></tr><tr><td>SecondLifeViewer!wWinMain</td><td>C:/a/viewer/viewer/indra/newview/llappviewerwin32.cpp(562)</td></tr><tr><td>SecondLifeViewer!invoke_main</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(118)</td></tr><tr><td>SecondLifeViewer!__scrt_common_main_seh</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(288)</td></tr><tr><td>kernel32!BaseThreadInitThunk</td><td> - </td></tr><tr><td>ntdll!RtlUserThreadStart</td><td> - </td></tr></table>
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5109</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @sl-service-account</code> (replace <code>20</code> with the amount, and <code>@sl-service-account</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by akleshchev**
Something weird is going on inside of a coroutine, but given their usual track record, adding protections to make sure they don't carry something over from a dead parent.

### CODE REVIEW

File: indra/newview/llpanelplaceprofile.cpp [hunk 1]
```diff
@@ -517,7 +517,7 @@ void LLPanelPlaceProfile::displaySelectedParcelInfo(LLParcel* parcel,
             std::string parcel_owner =
                 LLSLURL("agent", parcel->getOwnerID(), "inspect").getSLURLString();
             mParcelOwner->setText(parcel_owner);
-            LLAvatarNameCache::get(region->getOwner(), boost::bind(&LLPanelPlaceInfo::onAvatarNameCache, _1, _2, mRegionOwnerText));
+            mAvatarNameCacheConnection = LLAvatarNameCache::get(region->getOwner(), boost::bind(&LLPanelPlaceInfo::onAvatarNameCache, _1, _2, mRegionOwnerText));
```
Comment (maxim-productengine) [inline indra/newview/llpanelplaceprofile.cpp:520]: Do we need to disconnect it in destr?

Comment (akleshchev) [reply indra/newview/llpanelplaceprofile.cpp:520]: It's RAII scoped_connection, should do by itself.

**Review by marchcat — APPROVED** [review]
