### PR TITLE
#5157 fix crash in isHUDGroup

### LINKED ISSUE #5157: BugSplat Crash: SecondLifeViewer!LLSpatialGroup::isHUDGroup(140)
## BugSplat Crash Group 100603
[View Report Group](https://app.bugsplat.com/v2/group?stackKeyId=100603&database=SecondLife_Viewer_2018)
[View Report Details](https://app.bugsplat.com/v2/crash?id=1688937&database=SecondLife_Viewer_2018)
[View Report Attachments](https://app.bugsplat.com/v2/crash?id=1688937&database=SecondLife_Viewer_2018#attachments)

**Application:** Second Life Release
**Version:** 7.2.3.19375695301
**Error Code:** c0000005 Access violation

**Callstack:**
<table><tr><th>Function</th><th>File</th></tr><tr><td>SecondLifeViewer!LLSpatialGroup::isHUDGroup</td><td>C:/a/viewer/viewer/indra/newview/llspatialpartition.cpp(140)</td></tr><tr><td>SecondLifeViewer!LLPipeline::clearRebuildGroups</td><td>C:/a/viewer/viewer/indra/newview/pipeline.cpp(2735)</td></tr><tr><td>SecondLifeViewer!LLViewerTextureList::updateImages</td><td>C:/a/viewer/viewer/indra/newview/llviewertexturelist.cpp(818)</td></tr><tr><td>SecondLifeViewer!display</td><td>C:/a/viewer/viewer/indra/newview/llviewerdisplay.cpp(872)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::doFrame</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1514)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::frame</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1337)</td></tr><tr><td>SecondLifeViewer!wWinMain</td><td>C:/a/viewer/viewer/indra/newview/llappviewerwin32.cpp(523)</td></tr><tr><td>SecondLifeViewer!invoke_main</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(118)</td></tr><tr><td>SecondLifeViewer!__scrt_common_main_seh</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(288)</td></tr><tr><td>kernel32!BaseThreadInitThunk</td><td> - </td></tr><tr><td>ntdll!RtlUserThreadStart</td><td> - </td></tr></table>
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5157</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @sl-service-account</code> (replace <code>20</code> with the amount, and <code>@sl-service-account</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by maxim-productengine**
Crash seems to be happening during teleport (when not all objects were removed from deleted region) - so check spatial groups that have been marked but haven't been fully cleaned up yet.

### CODE REVIEW

**Review by marchcat — APPROVED** [review]

File: indra/newview/llspatialpartition.cpp [hunk 1]
```diff
@@ -135,8 +135,11 @@ void LLSpatialGroup::clearDrawMap()
     mDrawMap.clear();
 }
 
-bool LLSpatialGroup::isHUDGroup() const
+bool LLSpatialGroup::isHUDGroup()
 {
+    if (isDead())
```
Comment (akleshchev) [inline indra/newview/llspatialpartition.cpp]: What prevents isDead from becoming const? It's just a hasState(DEAD) check, which is const.

**Review by akleshchev — APPROVED** [review]

File: indra/newview/llspatialpartition.cpp (hunk 1 above)
Comment (maxim-productengine) [reply indra/newview/llspatialpartition.cpp]: You're probably right, let's leave `isHUDGroup()` as const
