### PR TITLE
#5541 Add safety checks for inventory save during shutdown

### LINKED ISSUE #5541: BugSplat Crash: SecondLifeViewer!std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::shared_ptr<LLControlCache<bool> > > > >::_Insert_node(734)
## BugSplat Crash Group 100540
[View Report Group](https://app.bugsplat.com/v2/group?stackKeyId=100540&database=SecondLife_Viewer_2018)
[View Report Details](https://app.bugsplat.com/v2/crash?id=1719485&database=SecondLife_Viewer_2018)
[View Report Attachments](https://app.bugsplat.com/v2/crash?id=1719485&database=SecondLife_Viewer_2018#attachments)

**Application:** Second Life Release
**Version:** 26.1.0.22641522367
**Error Code:** c0000005 Access violation

**Callstack:**
<table><tr><th>Function</th><th>File</th></tr><tr><td>SecondLifeViewer!std::_Tree_val<std::_Tree_simple_types<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,std::shared_ptr<LLControlCache<bool> > > > >::_Insert_node</td><td>C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207/include/xtree(734)</td></tr><tr><td>SecondLifeViewer!std::_Tree<std::_Tmap_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,LLSD,std::less<void>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,LLSD> >,0> >::_Emplace_hint</td><td>C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207/include/xtree(1082)</td></tr><tr><td>SecondLifeViewer!std::_Tree<std::_Tmap_traits<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,LLSD,std::less<void>,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,LLSD> >,0> >::emplace_hint</td><td>C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.44.35207/include/xtree(1092)</td></tr><tr><td>SecondLifeViewer!`anonymous namespace'::ImplMap::ref</td><td>C:/a/viewer/viewer/indra/llcommon/llsd.cpp(545)</td></tr><tr><td>SecondLifeViewer!LLSD::operator[]</td><td>C:/a/viewer/viewer/indra/llcommon/llsd.cpp(1053)</td></tr><tr><td>SecondLifeViewer!LLInventoryCategory::exportLLSD</td><td>C:/a/viewer/viewer/indra/llinventory/llinventory.cpp(1512)</td></tr><tr><td>SecondLifeViewer!LLViewerInventoryCategory::exportLLSD</td><td>C:/a/viewer/viewer/indra/newview/llviewerinventory.cpp(762)</td></tr><tr><td>SecondLifeViewer!LLInventoryModel::saveToFile</td><td>C:/a/viewer/viewer/indra/newview/llinventorymodel.cpp(3529)</td></tr><tr><td>SecondLifeViewer!LLInventoryModel::cache</td><td>C:/a/viewer/viewer/indra/newview/llinventorymodel.cpp(2381)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::disconnectViewer</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(5680)</td></tr><tr><td>SecondLifeViewer!LLAppViewer::cleanup</td><td>C:/a/viewer/viewer/indra/newview/llappviewer.cpp(1761)</td></tr><tr><td>SecondLifeViewer!LLAppViewerWin32::cleanup</td><td>C:/a/viewer/viewer/indra/newview/llappviewerwin32.cpp(813)</td></tr><tr><td>SecondLifeViewer!wWinMain</td><td>C:/a/viewer/viewer/indra/newview/llappviewerwin32.cpp(562)</td></tr><tr><td>SecondLifeViewer!invoke_main</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(118)</td></tr><tr><td>SecondLifeViewer!__scrt_common_main_seh</td><td>D:/a/_work/1/s/src/vctools/crt/vcstartup/src/startup/exe_common.inl(288)</td></tr><tr><td>kernel32!BaseThreadInitThunk</td><td> - </td></tr><tr><td>ntdll!RtlUserThreadStart</td><td> - </td></tr></table>
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5541</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @sl-service-account</code> (replace <code>20</code> with the amount, and <code>@sl-service-account</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by marchcat**
## Description

Likely cause is a use-after-free that corrupts std::map internals; the map insertion only exposes the failure (not the origin).

Defensive checks reduce the likelihood of a fatal exit, but root cause may need heap diagnostics to find the original corruption. However, given that this is a shutdown crash, it should be fine as is.

## Related Issues

#5541

### CODE REVIEW

File: indra/newview/llinventorymodel.cpp [hunk 1]
```diff
@@ -2383,10 +2383,22 @@ void LLInventoryModel::cache(
         items,
         INCLUDE_TRASH,
         can_cache);
+
+    if (categories.empty() && items.empty())
+    {
+        LL_INFOS(LOG_INV) << "Nothing to cache for " << parent_folder_id << LL_ENDL;
```
Comment (akleshchev) [inline indra/newview/llinventorymodel.cpp]: That's going to spam, some inventories contain thousands of folders.

Comment (marchcat) [reply indra/newview/llinventorymodel.cpp]: Makes sense, will remove or degrade to debug.
Thanks!

Comment (akleshchev) [reply indra/newview/llinventorymodel.cpp]: Ugh, sorry, this is top level function, it works only once...

Comment (akleshchev) [reply indra/newview/llinventorymodel.cpp]: It actually should be warns as model isn't supposed to be empty.

File: indra/newview/llinventorymodel.cpp [hunk 2]
```diff
@@ -2383,10 +2383,22 @@ void LLInventoryModel::cache(
...
+        return;
+    }
+
     // Use temporary file to avoid potential conflicts with other
     // instances (even a 'read only' instance unzips into a file)
     std::string temp_file = gDirUtilp->getTempFilename();
-    saveToFile(temp_file, categories, items);
+    if (!saveToFile(temp_file, categories, items))
```
Comment (akleshchev) [inline indra/newview/llinventorymodel.cpp:2396]: Suggestion: preallocate the file.

It is fine if there is some empty space at the end, gzip will sort that out. But estimating (based of previous cache? some average?) and preallocating file can speed up writing and minimize risk of issue mid save.

File: indra/newview/llinventorymodel.cpp [hunk 3]
```diff
@@ -3537,6 +3549,11 @@ bool LLInventoryModel::saveToFile(const std::string& filename,
         S32 cat_count = 0;
         for (auto& cat : categories)
         {
+            if (cat.isNull())
+            {
+                LL_WARNS(LOG_INV) << "Skipping null category during inventory save" << LL_ENDL;
```
Comment (akleshchev) [inline indra/newview/llinventorymodel.cpp:3554]: If possible, post a bit more details here please. Name of a parent, type, presense of a parent? I don't think null categories supposed to be in the model (fake root somehow got into model?).

**Review by akleshchev — APPROVED** [review]

File: indra/newview/llinventorymodel.cpp (hunk 2 above)
Comment (marchcat) [reply indra/newview/llinventorymodel.cpp:2396]: Preallocation could be a nice follow-up optimization, though the estimation is tricky since the existing gzip cache size isn't a reliable hint for the raw binary output. The temp file + cleanup pattern already covers the mid-save risk.

**Comment by akleshchev** [comment]
> Likely cause is a use-after-free that corrupts std::map internals; the map insertion only exposes the failure (not the origin).

Agree. something somewhere writes to a section of a memory it isn't supposed to touch.

File: indra/newview/llinventorymodel.cpp (hunk 3 above)
Comment (marchcat) [reply indra/newview/llinventorymodel.cpp:3554]: Not sure if we can do that. It's a null pointer so we won't be able to dereference it to get parent or other fields.
