### PR TITLE
Fix glTF collision volume bind reconstruction

### LINKED ISSUE #5639: differences between collada and glb imports
We are comparing rigged mesh export from Blender to Second Life via both .dae and .glb.

We can export both formats so that they behave identically in SL, but only when deformation is limited to the standard m* bones.

As soon as SL volume bones are also marked deform, the .glb result differs slightly from the .dae result after the mesh is worn on the avatar. The imported static meshes are identical. The difference appears only after wearing, when the SL rig actually deforms the mesh.

A few details:

-same source rig and mesh

- same visible export mesh in Blender before writing the file 

- same result in SL when volume bones are not deforming

- mismatch appears only when volume bones participate

- note that volume bones have the known non-neutral/rest-scale oddities

Does anyone know how SL’s .glb importer handles volume bones internally, especially their rest/bind transforms or scaling? We are trying to determine whether the difference comes from Blender glTF export, Avastar/Collada export assumptions, or SL’s handling of volume-bone skinning.

https://secondlife.canny.io/admin/feedback/bug-reports/p/differences-between-collada-and-glb-imports
<br/>
<hr/>

<details><summary>This repo is using Opire - what does it mean? 👇</summary><br/>💵 Everyone can add rewards for this issue commenting <code>/reward 100</code> (replace <code>100</code> with the amount).<br/>🕵️‍♂️ If someone starts working on this issue to earn the rewards, they can comment <code>/try</code> to let everyone know!<br/>🙌 And when they open the PR, they can comment <code>/claim #5639</code> either in the PR description or in a PR's comment.<br/><br/>🪙 Also, everyone can tip any user commenting <code>/tip 20 @canny[bot]</code> (replace <code>20</code> with the amount, and <code>@canny[bot]</code> with the user to tip).<br/><br/>📖 If you want to learn more, check out our <a href="https://docs.opire.dev">documentation</a>.</details>

### PR DESCRIPTION
**Pull request by gaiaclary**
## Description

The glTF importer rebuilt collision-volume override-rest matrices from the imported translation override and viewer-side scale only. That dropped the collision-volume rotation defined in `avatar_skeleton.xml` and produced incorrect inverse bind matrices for rotated collision volumes, especially torso volumes that use non-uniform scale.

The visible result was a mismatch between rigged mesh imported from `.glb` and the equivalent `.dae` upload.

This change fixes that in two places:

- `LLAvatarBoneInfo::getJointMatrix()` now interprets `avatar_skeleton.xml` Euler joint rotations as degrees.
- `LLGLTFLoader::buildOverrideMatrix()` now rebuilds collision-volume local rotation/scale directly from the raw viewer skeleton rotation and scale values, then applies the imported local translation override.

Regular joints stay on the existing translation-only override path, and alternate-bind translation handling is unchanged.

Why this is scoped this way:
- the issue is specific to collision volumes
- normal avatar joints were already importing correctly
- torso collision volumes use non-uniform scale, so the rotation/scale composition needs to match the viewer skeleton definition instead of being reduced to translation plus scale only

With the collision-volume basis restored, the final glTF import matches the working DAE path in local validation.

## Related Issues

Issue Link: relates to the glTF collision volume import issue discussed in the associated Second Life Feedback/Jira report at https://feedback.secondlife.com/bug-reports/p/differences-between-collada-and-glb-imports

## Checklist

- [x] I have provided a clear title and detailed description for this pull request.
- [ ] If useful, I have included media such as screenshots and video to show off my changes.
- [x] The PR is linked to a relevant issue with sufficient context.
- [x] I have tested the changes locally and verified they work as intended.
- [ ] All new and existing tests pass.
- [x] Code follows the project's style guidelines.
- [ ] Documentation has been updated if needed.
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have reviewed the contributing guidelines.

## Additional Notes

Local validation compared `.glb` and `.dae` imports of the same rigged mesh with deforming collision volumes. Before this change, glTF imports showed visible torso/chest deviations. After this change, the glTF import matched the DAE import in those cases.

### CODE REVIEW

**Review by akleshchev — APPROVED** [review]

File: indra/llappearance/llavatarappearance.cpp [hunk 1]
```diff
@@ -1647,10 +1647,10 @@ glm::mat4 LLAvatarBoneInfo::getJointMatrix()
...
     // 1. Scaling
     mat = glm::scale(mat, glm::vec3(mScale[0], mScale[1], mScale[2]));
-    // 2. Rotation (Euler angles rad)
-    mat = glm::rotate(mat, mRot[0], glm::vec3(1, 0, 0));
-    mat = glm::rotate(mat, mRot[1], glm::vec3(0, 1, 0));
-    mat = glm::rotate(mat, mRot[2], glm::vec3(0, 0, 1));
+    // 2. Rotation (avatar_skeleton.xml stores Euler angles in degrees)
+    mat = glm::rotate(mat, glm::radians(mRot[0]), glm::vec3(1, 0, 0));
+    mat = glm::rotate(mat, glm::radians(mRot[1]), glm::vec3(0, 1, 0));
+    mat = glm::rotate(mat, glm::radians(mRot[2]), glm::vec3(0, 0, 1));
```
Comment (akleshchev) [inline indra/llappearance/llavatarappearance.cpp:1653]: Thanks, I missed that mayaQ does degree to rad convertion and alsmost everything is 0 so it didn't pop up as a problem for me.

Please, consider adding 'in degrees' comment near the mRot declaration.
